<a href="https://colab.research.google.com/github/Lecture-CPE/308/blob/2562-2/w12/colab/eigenvalues_eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalues and Eigenvectors

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Definition

Let $A$ be a square matrix. A non-zero vector $\mathbf{v}$ is an [eigenvector](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) for $A$ with [eigenvalue](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) $\lambda$ if

$$
A\mathbf{v} = \lambda \mathbf{v}
$$

Rearranging the equation, we see that $\mathbf{v}$ is a solution of the homogeneous system of equations

$$
\left( A - \lambda I \right) \mathbf{v} = \mathbf{0}
$$

where $I$ is the identity matrix of size $n$. Non-trivial solutions exist only if the matrix $A - \lambda I$ is singular which means $\mathrm{det}(A - \lambda I) = 0$. Therefore eigenvalues of $A$ are roots of the [characteristic polynomial](https://en.wikipedia.org/wiki/Characteristic_polynomial)

$$
p(\lambda) = \mathrm{det}(A - \lambda I)
$$

## scipy.linalg.eig

The function [`scipy.linalg.eig`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html) computes eigenvalues and eigenvectors of a square matrix $A$.

Let's consider a simple example with a diagonal matrix:

In [2]:
A = np.array([[3,0],[8,-1]])
print(A)

[[ 3  0]
 [ 8 -1]]


The function `la.eig` returns a tuple `(eigvals,eigvecs)` where `eigvals` is a 1D NumPy array of complex numbers giving the eigenvalues of $A$, and `eigvecs` is a 2D NumPy array with the corresponding eigenvectors in the columns:

In [5]:
B = np.array([[1],[2]])
print(B)

[[1]
 [2]]


In [6]:
C = np.array([[0],[1]])
print(C)

[[0]
 [1]]


นำ Matrix A คูณด้วย Vector B 
\begin{equation}
\begin{bmatrix}
3&0\\
8&-1\\
\end{bmatrix}\begin{bmatrix}1\\2 \end{bmatrix} = D
\end{equation}

In [9]:
D=A@B
print(D)

[[3]
 [6]]


จัดรูปดีๆ จากตัวอย่างนี้ ดึงตัวร่วมออก จะเห็นว่า matrix A คู่ vector B จะทำให้ได้ ตัวขยาย vector B ขนาด 3 เท่า

เรียกตัวคูณ ในที่นี้คือเลข 3 ว่าเป็น **ค่าลักษณะเฉพาะ** (Eigenvalue) และเรียก เวกเตอร์ B ว่า **เวกเตอร์ลักษณะเฉพาะ** (Eigenvector)

\begin{equation}
\begin{bmatrix}
3&0\\
8&-1\\
\end{bmatrix}\begin{bmatrix}1\\2 \end{bmatrix} = \begin{bmatrix} 3\\6 \end{bmatrix} = 3\begin{bmatrix} 1\\2\end{bmatrix}
\end{equation}

\begin{equation}
\textbf{A}x = \lambda x = \lambda I_n x 
\end{equation}

\begin{equation}
\begin{aligned}
\textbf{A}x - \lambda I_n x  = (\textbf{A}-\lambda I_n)x &= 0 \\
(\lambda I_n - A)x &= 0
\end{aligned}
\end{equation}

∴ $\lambda$ เรียกว่า ค่าลักษณะเฉพาะเมื่อระบบ $(\lambda I_n - A)x = 0$
ไม่มีผลเฉลย

ถ้าระบบมีเฉลยที่ชัด แปลว่า x=0 ทำให้ไม่มีข้อมูล  ที่เราต้องการคือ x!=0 

จะเป็นได้นั้น 
\begin{equation}
det(\lambda I_n - A) = 0 
\end{equation}
เรียกสมการด้านบนว่า **สมการลักษณะเฉพาะ**
เรียกสมการซ้ายมือ(ส่วน determinant) ว่า **พหุนามลักษณะเฉพาะ**

### ตัวอย่าง จงหาค่าลักษณะเฉพาะ(Eigenvalue) ทั้งหมด

\begin{equation}
\textbf{A} = \begin{bmatrix} 0&1&0 \\
                             0&0&1\\
                             4&-17&8
             \end{bmatrix}
             \end{equation}

\begin{equation}
\begin{aligned}
det(xI_3 - A) &= \begin{vmatrix} x & -1 & 0 \\
                                0 & x & -1\\
                                -4 &17&(x-8)\\
                \end{vmatrix} \\
              &= x^3-8x^2+17x-4 = 0 \\
              &= (x-4)(x^2-4x+1) = 0
 \end{aligned}
\end{equation}

$x=2-\sqrt{3}$, $x=2+\sqrt{3}$ และ  $x=4$


In [15]:
A=np.array([[0,1,0],[0,0,1],[4,-17,8]])
results = la.eig(A)
print(A)

[[  0   1   0]
 [  0   0   1]
 [  4 -17   8]]


ค่าลักษณะเฉพาะ(eigenvalues)ของ $\textbf{A}$ ทั้งหมดมีค่าเท่ากับ:

In [21]:
print(results[0])

[0.26794919+0.j 3.73205081+0.j 4.        +0.j]


ดังนั้น เวกเตอร์เฉพาะ(eigenvectors) เท่ากับ:

In [22]:
print(results[1])

[[-0.96361137 -0.06918418 -0.06052275]
 [-0.25819889 -0.25819889 -0.24209101]
 [-0.06918418 -0.96361137 -0.96836405]]


We can [unpack the tuple](../../python/sequences/#unpacking-a-sequence):

In [20]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

[0.26794919+0.j 3.73205081+0.j 4.        +0.j]


In [0]:
print(eigvecs)

[[1. 0.]
 [0. 1.]]


If we know that the eigenvalues are real numbers (ie. if $A$ is symmetric), then we can use the NumPy array method `.real` to convert the array of eigenvalues to real numbers:

In [23]:
eigvals = eigvals.real
print(eigvals)

[0.26794919 3.73205081 4.        ]


Notice that the position of an eigenvalue in the array `eigvals` correspond to the column in `eigvecs` with its eigenvector:

In [29]:
lambda1 = eigvals[1]
print(lambda1)

3.7320508075688448


In [34]:
v1 = eigvecs[:,1].reshape(3,1)
print(v1)

[[-0.06918418]
 [-0.25819889]
 [-0.96361137]]


In [0]:
A @ v1

array([[ 0.],
       [-2.]])

In [0]:
lambda1 * v1

array([[-0.],
       [-2.]])

## Examples

### Symmetric Matrices

The eigenvalues of a [symmetric matrix](https://en.wikipedia.org/wiki/Symmetric_matrix) are always real and the eigenvectors are always orthogonal! Let's verify these facts with some random matrices:

In [0]:
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[7 0 6 2]
 [9 5 1 3]
 [0 2 2 5]
 [6 8 8 6]]


Create the symmetric matrix $S = P P^T$:

In [0]:
S = P @ P.T
print(S)

[[ 89  75  22 102]
 [ 75 116  27 120]
 [ 22  27  33  62]
 [102 120  62 200]]


Let's unpack the eigenvalues and eigenvectors of $S$:

In [0]:
evals, evecs = la.eig(S)
print(evals)

[361.75382302+0.j  42.74593101+0.j  26.33718907+0.j   7.16305691+0.j]


The eigenvalues all have zero imaginary part and so they are indeed real numbers:

In [0]:
evals = evals.real
print(evals)

[361.75382302  42.74593101  26.33718907   7.16305691]


The corresponding eigenvectors of $A$ are:

In [0]:
print(evecs)

[[-0.42552429 -0.42476765  0.76464379 -0.23199439]
 [-0.50507589 -0.54267519 -0.64193252 -0.19576676]
 [-0.20612674  0.54869183 -0.05515612 -0.80833585]
 [-0.72203822  0.4733005   0.01415338  0.50442752]]


Let's check that the eigenvectors are orthogonal to each other:

In [0]:
v1 = evecs[:,0] # First column is the first eigenvector
print(v1)

[-0.42552429 -0.50507589 -0.20612674 -0.72203822]


In [0]:
v2 = evecs[:,1] # Second column is the second eigenvector
print(v2)

[-0.42476765 -0.54267519  0.54869183  0.4733005 ]


In [0]:
v1 @ v2

-1.1102230246251565e-16

The dot product of eigenvectors $\mathbf{v}_1$ and $\mathbf{v}_2$ is zero (the number above is <em>very</em> close to zero and is due to rounding errors in the computations) and so they are orthogonal!

### Diagonalization

A square matrix $M$ is [diagonalizable](https://en.wikipedia.org/wiki/Diagonalizable_matrix) if it is similar to a diagonal matrix. In other words, $M$ is diagonalizable if there exists an invertible matrix $P$ such that $D = P^{-1}MP$ is a diagonal matrix.

A beautiful result in linear algebra is that a square matrix $M$ of size $n$ is diagonalizable if and only if $M$ has $n$ independent eigevectors. Furthermore, $M = PDP^{-1}$ where the columns of $P$ are the eigenvectors of $M$ and $D$ has corresponding eigenvalues along the diagonal.

Let's use this to construct a matrix with given eigenvalues $\lambda_1 = 3, \lambda_2 = 1$, and eigenvectors $v_1 = [1,1]^T, v_2 = [1,-1]^T$.

In [0]:
P = np.array([[1,1],[1,-1]])
print(P)

[[ 1  1]
 [ 1 -1]]


In [0]:
D = np.diag((3,1))
print(D)

[[3 0]
 [0 1]]


In [0]:
M = P @ D @ la.inv(P)
print(M)

[[2. 1.]
 [1. 2.]]


Let's verify that the eigenvalues of $M$ are 3 and 1:

In [0]:
evals, evecs = la.eig(M)
print(evals)

[3.+0.j 1.+0.j]


Verify the eigenvectors:

In [0]:
print(evecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### Matrix Powers

Let $M$ be a square matrix. Computing powers of $M$ by matrix multiplication

$$
M^k = \underbrace{M M \cdots M}_k
$$

is computationally expensive. Instead, let's use diagonalization to compute $M^k$ more efficiently

$$
M^k = \left( P D P^{-1} \right)^k  = \underbrace{P D P^{-1} P D P^{-1} \cdots P D P^{-1}}_k = P D^k P^{-1}
$$

Let's compute $M^{20}$ both ways and compare execution time.

In [0]:
Pinv = la.inv(P)

In [0]:
k = 20

In [0]:
%%timeit
result = M.copy()
for _ in range(1,k):
    result = result @ M

42.1 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Let's use diagonalization to do the same computation.

In [0]:
%%timeit
P @ D**k @ Pinv

6.42 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Diagonalization computes $M^{k}$ much faster!

## Exercises

*Under construction*