<a href="https://colab.research.google.com/github/Lecture-CPE/308/blob/2562-2/w12/colab/Matrix_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Operations and Functions


In [0]:
import numpy as np
import scipy.linalg as la

กำหนด Matrix A = [ 1 3 -2 1 ]


In [0]:
A = np.array([1,3,-2,1])
print(A)

กำหนด Matrix 
  \begin{align}
  B=\begin{bmatrix}1&2 \\3&7\\-1&5
  \end{bmatrix}
  \end{align}

In [0]:
B = np.array([[1,2],[3,7],[-1,5]])
print(B)

ข้อมูล Matrix 
- จำนวน dimension (B.ndim)
- รูปของ matrix (B.shape)
- จำนวนสมาชิก (B.size)

In [0]:
B.ndim

2

In [0]:
B.shape

(3, 2)

In [0]:
B.size

6

เลือกข้อมูลตาม คอลัมน์ (col)


In [0]:
col = B[:,1]
print(col)

[2 7 5]


In [0]:
col.ndim

1

In [0]:
col.size

3

เลือก แถว (row)


In [0]:
row=B[0,:]
print(row)

[1 2]


## Arithmetic Operator
ตัวดำเนินการพื้นฐาน +,-,/, * และ ** ใช้ได้กับ Matrix



In [0]:
M = np.array([[3,4],[-1,5]])
print(M)

In [0]:
M+M

array([[ 6,  8],
       [-2, 10]])

In [0]:
M*M

array([[ 9, 16],
       [ 1, 25]])

## การคูณ Matrix
ใช้เครื่องหมาย @ เช่น 


In [0]:
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's compute $2I + 3A - AB$ for

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

and $I$ is the identity matrix of size 2:

In [0]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [0]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [0]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [0]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

## Matrix Powers

ใช้ฟังก์ชัน matrix power จากไลบรารี่ matrix_power


In [0]:
from numpy.linalg import matrix_power as mpow

In [0]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [0]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

In [0]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [0]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [0]:
M@M@M

array([[-17, 180],
       [-45,  73]])

### Transpose
ใช้คำสั่ง .T เพื่อทำ Transpose matrix


In [0]:
print(M)

[[ 3  4]
 [-1  5]]


In [0]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


symmetric matrix 
$MM^T$

In [0]:
M @ M.T

array([[25, 17],
       [17, 26]])

### Inverse matrix
ใช้ฟังก์ชั่น scipy.linalg.inv



In [0]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [0]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Determinant
We find the determinant using the function scipy.linalg.det:


In [47]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [48]:
la.det(A)

-2.0

## Exercises

1. Write a function which takes an input parameter $A$, $i$ and $j$ and returns the dot product of the $i$th and $j$th row (indexing starts at 0).
2. Compute the matrix equation $AB + 2B^2 - I$ for matrices $A = \begin{bmatrix} 3 & 4 \\\ -1 & 2 \end{bmatrix}$ and $B = \begin{bmatrix} 5 & 2 \\\ 8 & -3 \end{bmatrix}$.              